const { Client } = require('pg');
const { DB } = require('./config');

(async () => {

  const usersTableStmt = `
    CREATE TABLE  IF NOT EXISTS users (
        id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        email       VARCHAR(50)     NOT NULL,
        password    TEXT            NOT NULL,
        firstName   VARCHAR(50)     NOT NULL,
        lastName    VARCHAR(50)     NOT NULL,
        created     DATE,
        modified    DATE
    );
  `

  const ordersTableStmt = `
    CREATE TABLE IF NOT EXISTS orders (
        id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        userId      INT             NOT NULL,
        total       BIGINT          NOT NULL,
        status      VARCHAR(50)     NOT NULL,
        created     DATE,
        modified    DATE
    );
  `

  const productsTableStmt = `
    CREATE TABLE IF NOT EXISTS products (
        id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        name        VARCHAR(50)     NOT NULL,
        price       BIGINT          NOT NULL,
        description TEXT,
        status      VARCHAR(50)     NOT NULL,
        created     DATE,
        modified    DATE
    );
  `

  const cartsTableStmt = `
    CREATE TABLE IF NOT EXISTS carts (
        id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        userId      INT             NOT NULL,
        created     DATE,
        modified    DATE
    );
  `

  const cartItemsTableStmt = `
    CREATE TABLE IF NOT EXISTS cartItems (
        id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        productId   INT             NOT NULL,
        qty         INT             NOT NULL,
        cartId      INT             NOT NULL
    );
  `

  const orderItemsTableStmt = `
    CREATE TABLE IF NOT EXISTS orderItems (
        id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        productId   INT             NOT NULL,
        qty         INT             NOT NULL,
        orderId     INT             NOT NULL
    );
  `

  try {
    const db = new Client({
      user: DB.PGUSER,
      host: DB.PGHOST,
      database: DB.PGDATABASE,
      password: DB.PGPASSWORD,
      port: DB.PGPORT
    });

    await db.connect();

    // Create tables on database
    await db.query(usersTableStmt);
    await db.query(productsTableStmt);
    await db.query(ordersTableStmt);
    await db.query(orderItemsTableStmt);
    await db.query(cartsTableStmt);
    await db.query(cartItemsTableStmt);

    await db.end();

  } catch(err) {
    console.log("ERROR CREATING ONE OR MORE TABLES: ", err);
  }

})();